import { PublicStatement } from "./types";

export const PUBLIC_STATEMENTS: Record<string, PublicStatement[]> = {
  mccall: [
    {
      date: "2025-12-08",
      source: "Transylvania Times",
      type: "news",
      text: "Elected Chair of the Board of Commissioners, succeeding Jason Chappell.",
      url: "https://www.transylvaniatimes.com/news/mccall-chapman-to-lead-county-commissioners/article_e7e12ac8-9d7a-4f33-80a4-6f543bd5300e.html",
      categories: ["governance"],
    },
    {
      date: "2026-02-09",
      source: "Meeting — Commissioners' Comments",
      type: "statement",
      text: "Addressed Owen Carson's public comment about the County Planner vacancy, confirming the position will be filled.",
      categories: ["governance", "housing"],
    },
    {
      date: "2026-02-09",
      source: "Meeting — Budget Discussion",
      type: "statement",
      text: "Pushed for discussion on timing of a potential ¼-cent sales tax referendum. Praised staff for securing the $7M landfill grant, saving approximately six cents on the property tax rate.",
      categories: ["fiscal"],
    },
  ],
  chapman: [
    {
      date: "2025-12-08",
      source: "Transylvania Times",
      type: "news",
      text: "Elected Vice-Chair of the Board of Commissioners, taking over from Jake Dalton.",
      url: "https://www.transylvaniatimes.com/news/mccall-chapman-to-lead-county-commissioners/article_e7e12ac8-9d7a-4f33-80a4-6f543bd5300e.html",
      categories: ["governance"],
    },
    {
      date: "2026-02-09",
      source: "Meeting — Commissioners' Comments",
      type: "statement",
      text: "Announced screening of 'Rising Above Helene' documentary by NCACC, March 17 at Transylvania County Library.",
      categories: ["community", "recovery"],
    },
    {
      date: "2026-02-09",
      source: "Meeting — Budget Discussion",
      type: "statement",
      text: "Noted property tax reform is a growing national topic. Referenced NCACC district directors meeting where Florida reps discussed similar challenges.",
      categories: ["fiscal"],
    },
    {
      date: "2025-06-09",
      source: "Meeting Minutes",
      type: "statement",
      text: "Proposed additional budget workshop to review public feedback on FY2026 budget.",
      categories: ["fiscal", "governance"],
    },
  ],
  chappell: [
    {
      date: "2026-02-09",
      source: "Meeting — Commissioners' Comments",
      type: "statement",
      text: "Cautioned citizens about social media misinformation on county matters. Clarified that road maintenance is NCDOT's responsibility.",
      categories: ["governance"],
    },
    {
      date: "2026-02-09",
      source: "Meeting — New Business",
      type: "statement",
      text: "Initiated letter to NC General Assembly advocating for a waiver on virtual instructional day limits for WNC schools.",
      categories: ["schools", "governance"],
    },
    {
      date: "2025-06-09",
      source: "Meeting Minutes (read by McCall)",
      type: "statement",
      text: "Written statement supporting FY2026 budget — his 20th budget cycle. Highlighted single fire tax district and communication tower funding.",
      categories: ["fiscal", "safety"],
    },
    {
      date: "2025-05-12",
      source: "Meeting Minutes",
      type: "statement",
      text: "Emphasized importance of advocating in Raleigh for flexibility in how state appropriation funds can be used for local capital needs.",
      categories: ["fiscal", "infrastructure"],
    },
  ],
  dalton: [
    {
      date: "2025-12-28",
      source: "Transylvania Times",
      type: "news",
      text: "Announced he will not seek another term on the Board of Commissioners.",
      url: "https://www.transylvaniatimes.com/news/sheriff-owenby-faces-no-official-opposition/article_dd5fd18d-4e58-4778-bcf9-825f72380725.html",
      categories: ["governance"],
    },
    {
      date: "2026-02-09",
      source: "Meeting — Budget Discussion",
      type: "statement",
      text: "Advocated for differentiated tax rate on vacation/second homes (like VA, TN, SC). Serves on NCACC Tax & Finance Subcommittee.",
      categories: ["fiscal", "housing"],
    },
    {
      date: "2026-02-09",
      source: "Meeting — Budget Discussion",
      type: "statement",
      text: "Pushed for increased federal PILT funding — more than 2/3 of county land doesn't generate property taxes.",
      categories: ["fiscal", "environment"],
    },
    {
      date: "2025-08-25",
      source: "Meeting Minutes",
      type: "statement",
      text: "Questioned differences between commercial and private mobile home valuations during reappraisal discussion.",
      categories: ["fiscal"],
    },
    {
      date: "2025-06-02",
      source: "Budget Workshop",
      type: "statement",
      text: "Noted fire department budget subcommittee had already pared down requests. Pressed on county 401K contributions for non-law-enforcement employees.",
      categories: ["fiscal", "safety"],
    },
  ],
  mckelvey: [
    {
      date: "2025-12-28",
      source: "Transylvania Times",
      type: "news",
      text: "Announced he will not seek another term. His seat and Dalton's are the two open seats in November 2026.",
      url: "https://www.transylvaniatimes.com/news/sheriff-owenby-faces-no-official-opposition/article_dd5fd18d-4e58-4778-bcf9-825f72380725.html",
      categories: ["governance"],
    },
    {
      date: "2026-02-09",
      source: "Meeting — Budget Discussion",
      type: "statement",
      text: "Asked about putting ¼-cent sales tax on 2026 ballot. Suggested combining with fee-based solid waste could cut property taxes ~3 cents.",
      categories: ["fiscal"],
    },
    {
      date: "2025-08-25",
      source: "Meeting Minutes",
      type: "statement",
      text: "Shared constituent concerns about mobile home valuations, comparing to classic car valuation. Stressed fairness for single-wide home residents.",
      categories: ["fiscal", "housing"],
    },
    {
      date: "2025-06-02",
      source: "Budget Workshop",
      type: "statement",
      text: "Preferred fire tax rate below 7 cents. Raised concern that allocated fire funds may not result in hires since departments are independent entities.",
      categories: ["fiscal", "safety"],
    },
  ],
};
